
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
  tomcat:
    connection-timeout: -1
logging:
  level:
    '[com.fastcampus.minischeduler]': DEBUG
    '[org.hibernate.type]': TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/minischeduler
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:templates
    suffix: .html
    mode: HTML
    check-template-location: true
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: aws
